export const actionNames = {
  equipment_distribute: 'توزيع معدة',
  equipment_return: 'إعادة معدة',
  equipment_retire: 'إخراج معدة من الخدمة',
  workshop_intake: 'إرسال معدة للورشة',
  workshop_return: 'إعادة معدة من الورشة',
  ammunition_distribute: 'توزيع ذخيرة',
  ammunition_return: 'إعادة ذخيرة',
  ammunition_warehouse_add: 'توريد ذخيرة',
  ammunition_threshold_update: 'تعديل الحد الأدنى',
  ammunition_scrap: 'إعدام ذخيرة',
  personnel_assign: 'تعيين كادر',
  personnel_return: 'إعادة كادر',
  personnel_transfer: 'نقل كادر',
  rotation_update: 'تعديل تاريخ الاستحقاق',
  platform_created: 'إنشاء منصة',
  platform_updated: 'تعديل منصة',
  platform_deleted: 'حذف منصة',
  platform_disabled: 'تعطيل منصة',
  platform_enabled: 'تفعيل منصة',
  course_created: 'إنشاء دورة',
  course_updated: 'تعديل دورة',
  course_deleted: 'حذف دورة',
  trainee_added: 'إضافة دارس',
  trainee_removed: 'إزالة دارس',
  login: 'تسجيل دخول',
  logout: 'تسجيل خروج',
  setting_updated: 'تعديل إعداد',
};

export const actionColors = {
  equipment_distribute: 'blue',
  equipment_return: 'green',
  equipment_retire: 'red',
  workshop_intake: 'yellow',
  workshop_return: 'green',
  ammunition_distribute: 'blue',
  ammunition_return: 'green',
  ammunition_warehouse_add: 'green',
  ammunition_threshold_update: 'yellow',
  ammunition_scrap: 'red',
  personnel_assign: 'blue',
  personnel_return: 'green',
  personnel_transfer: 'purple',
  rotation_update: 'yellow',
  platform_created: 'green',
  platform_updated: 'blue',
  platform_deleted: 'red',
  platform_disabled: 'red',
  platform_enabled: 'green',
  course_created: 'green',
  course_updated: 'blue',
  course_deleted: 'red',
  trainee_added: 'blue',
  trainee_removed: 'red',
  login: 'blue',
  logout: 'gray',
  setting_updated: 'yellow',
};